# Stochastic Gradient Descent Lecture Tutorial

In [ ]:
import numpy as np

n, m = 10, 20
x = np.random.uniform(-5, 5, [n])
A = np.random.normal(0, 1/pow(m, 1/2), (m, n))
eps = np.random.normal(0, 1/m, [m])

In [ ]:
y = A @ x + eps

the gradient is
$$
\nabla_z  \frac{1}{2 m} || A z - y ||_2^2 = \frac{1}{m} A^T (A z - y)
$$
and then
$$
\frac{1}{m} A^T (A z - y) = 0 \implies z = (A^T A)^{-1} A^T y
$$

In [ ]:
analytical_sol = np.linalg.inv(A.transpose() @ A) @ A.transpose() @ y

In [ ]:
analytical_sol

array([ 1.58213005,  1.39532293, -9.43256955, -6.96543317,  3.42186674,
       -8.38594082,  1.67670828, -3.87800327, 10.98869507,  1.50748075])

In [ ]:
def loss(z):
    return (1/(2*m)) * np.linalg.norm(A @ z - y)**2

## The numerical gradient implementation

to approximate $\partial_i$ we use slope for small $h$
$$
\frac{\text{loss}(x + h e_i) - \text{loss}(x)}{h}
$$

In [ ]:
x = np.array([1]*n) # a vector in R^n
h = 10**(-10)

## for diff_1

dloss_1 = (loss(np.array([x[0]+h, *x[1:]])) - loss(x)) / h # d_1 loss (x)
dloss_1

np.float64(-0.03664624159682717)

In [ ]:
x = np.array([1]*n) # a vector in R^n
h = 10**(-10)

num_gradient = lambda x: np.array([
    (loss(np.array( [*x[:i], x[i]+h, *x[i+1:]] )) - loss(x)) / h # (loss(x+h e_1) - loss(x))/h
    for i in range(n)
])
num_gradient(x)

array([-3.66462416e-02,  8.11173351e-02,  9.87654403e-02,  2.71036527e-01,
        6.80344669e-02,  1.77733384e-01,  1.59872116e-04, -4.63984406e-02,
       -3.27826655e-02, -1.36903822e-01])

In [ ]:
x = np.array([1]*n) # a vector in R^n

exact_gradient = lambda x: (1/m) * np.array(A.transpose() @ (A @ x - y))
exact_gradient(x)

array([-3.66359864e-02,  8.11190403e-02,  9.87798997e-02,  2.71058130e-01,
        6.80300649e-02,  1.77734144e-01,  1.67020058e-04, -4.63948017e-02,
       -3.27772475e-02, -1.36908506e-01])

## Gradient descent implementation

In [ ]:
N = 100000
eta = 1

x = np.array([0]*n) # a vector in R^n
for i in range(N):
    x = x - eta * exact_gradient(x) # gradient update step
x

array([ 1.58213005,  1.39532293, -9.43256955, -6.96543317,  3.42186674,
       -8.38594082,  1.67670828, -3.87800327, 10.98869507,  1.50748075])

In [ ]:
# the analytical solution computed above.
analytical_sol

array([ 1.58213005,  1.39532293, -9.43256955, -6.96543317,  3.42186674,
       -8.38594082,  1.67670828, -3.87800327, 10.98869507,  1.50748075])

## Conclusion

We can see that the analytical solution and the solution found by gradient descent perfectly match and the $\ell_2$-norm of their difference 0